account/urls.py
from django.conf.urls import url
from django.contrib import admin

from .views import *

urlpatterns = [
	url(r'^$', home, name='home'),
	url(r'^register/$', register_view, name='register'),
    url(r'^login/$', login_view, name='login'),
    url(r'^logout/$', logout_view, name='logout'),
    url(r'^ajax/get_invites/', get_invites, name='get_invites'),
    url(r'^notifications/$', notifications, name='notifications'),
    url(r'^notifications/last/$', last_notifications, name='last_notifications'),
    url(r'^notifications/check/$', check_notifications, name='check_notifications'),
    url(r'^accept_invitation/(?P<id>\d+)/$', accept_invitation, name='invite_accept'),
    url(r'^reject_invitation/(?P<id>\d+)/$', reject_invitation, name='invite_reject'),  
    # url(r'^team/create$', create_team, name='team'),
]

pdf/urls.py
from django.conf.urls import url
from django.contrib import admin

from .views import (
	pdf_create,
	pdf_detail,
	pdf_update,
	PDFContributorsToggle,
	)

urlpatterns = [
    url(r'^create/$', pdf_create, name='create'),
    url(r'^(?P<slug>[\w-]+)/$', pdf_detail, name='detail'),
    url(r'^(?P<slug>[\w-]+)/edit/$', pdf_update, name='update'),
    url(r'^(?P<pdf>[\w-]+)/contibutor/(?P<username>[\w]+)$', PDFContributorsToggle.as_view(), name='contributor-toggle'),
    # url(r'^(?P<slug>[\w-]+)/delete/$', post_delete),
    #url(r'^posts/$', "<appname>.views.<function_name>"),
]

pdf_versioning/urls.py
from django.conf import settings
from django.conf.urls import url,include
from django.conf.urls.static import static
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
	url(r'^', include('account.urls', namespace='accounts')),
	url(r'^', include('pdf.urls', namespace='pdfs')),
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

pdf/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.conf import settings
from django.contrib.contenttypes.models import ContentType
from django.core.urlresolvers import reverse
from django.db import models
from django.db.models.signals import pre_save
from django.utils import timezone
from django.utils.safestring import mark_safe
from django.utils.text import slugify

import reversion


# Create your models here.

# class PDFManager(models.Manager):
#     def active(self, *args, **kwargs):
#         # Post.objects.all() = super(PostManager, self).all()
#         return super(PDFManager, self).filter(publish__lte=timezone.now())


def upload_location(instance, filename):
    #filebase, extension = filename.split(".")
    #return "%s/%s.%s" %(instance.id, instance.id, extension)
    PDFModel = instance.__class__
    
    """
    instance.__class__ gets the model Post. We must use this method because the model is defined below.
    Then create a queryset ordered by the "id"s of each object, 
    Then we get the last object in the queryset with `.last()`
    Which will give us the most recently created Model instance
    We add 1 to it, so we get what should be the same id as the the post we are creating.
    """
    return "%s/%s" %(instance.user, filename)

@reversion.register()
class PDF(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, default=1)
    title = models.CharField(max_length=120)
    slug = models.SlugField(unique=True)
    file = models.FileField(upload_to=upload_location, null=False, blank=True, max_length=500)
    contributor = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name="contributors", default=1)
    comment = models.CharField(max_length=50)
    # publish = models.DateField(auto_now=False, auto_now_add=False)
    updated = models.DateTimeField(auto_now=True, auto_now_add=False)
    timestamp = models.DateTimeField(auto_now=False, auto_now_add=True)

    # objects = PDFManager()

    def __unicode__(self):
        return self.title

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse("pdfs:detail", kwargs={"slug": self.slug})

    class Meta:
        ordering = ["-timestamp", "-updated"]



    @property
    def get_content_type(self):
        instance = self
        content_type = ContentType.objects.get_for_model(instance.__class__)
        return content_type

def create_slug(instance, new_slug=None):
    slug = slugify(instance.title)
    if new_slug is not None:
        slug = new_slug
    qs = PDF.objects.filter(slug=slug).order_by("-id")
    exists = qs.exists()
    if exists:
        new_slug = "%s-%s" %(slug, qs.first().id)
        return create_slug(instance, new_slug=new_slug)
    return slug

def pre_save_pdf_receiver(sender, instance, *args, **kwargs):
    if not instance.slug:
        instance.slug = create_slug(instance)


pre_save.connect(pre_save_pdf_receiver, sender=PDF)

pdf/forms.py
from django import forms

# from pagedown.widgets import PagedownWidget

from .models import PDF


class PDFForm(forms.ModelForm):
    # title = forms.CharField(widget=PagedownWidget(show_preview=False))
    title = forms.CharField(widget=forms.TextInput(attrs={"type": "text", "class": "form-control",
                                                         "placeholder":"PDF title"}),
                                max_length=30,
                                required=True,
                               )
    comment = forms.CharField(widget=forms.TextInput(attrs={"type": "text", "class": "form-control",
                                                         "placeholder":"Commit Message"}),
                                max_length=30,
                                required=True,
                               )
    class Meta:
        model = PDF
        fields = [
            "title",
            "comment",
            "file",
            ]

pdf/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

try:
    from urllib import quote_plus #python 2
except:
    pass

try:
    from urllib.parse import quote_plus #python 3
except: 
    pass

from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.contrib.contenttypes.models import ContentType
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger

from django.db.models import Q
from django.http import HttpResponse, HttpResponseRedirect, Http404
from django.shortcuts import render, get_object_or_404, redirect
from django.views.generic import RedirectView
from django.utils import timezone
from django.shortcuts import render

import reversion
from reversion.models import Version

from .forms import PDFForm
from .models import PDF
# Create your views here.

@login_required
def pdf_create(request):
	form = PDFForm(request.POST or None, request.FILES or None)
	print form
	if form.is_valid():
		with reversion.create_revision():
			instance = form.save(commit=False)
			instance.user = request.user
			instance.save()
			reversion.set_user(request.user)
    		# reversion.set_comment(instance.comment)
		# message success
		messages.success(request, "Successfully Created")
		return HttpResponseRedirect(instance.get_absolute_url())
	context = {
		"form": form,
	}
	return render(request, "pdf_form.html", context)

@login_required
def pdf_detail(request, slug=None):
	instance = get_object_or_404(PDF, slug=slug)
	# Load a queryset of versions for a specific model instance.
	versions = Version.objects.get_for_object(instance)
	# if instance.publish > timezone.now().date() or instance.draft:
	# 	if not request.user.is_staff or not request.user.is_superuser:
	# 		raise Http404
	share_string = quote_plus(instance.title)

	initial_data = {
			"content_type": instance.get_content_type,
			"object_id": instance.id,
			}

	context = {
		"title": instance.title,
		"instance": instance,
		"share_string": share_string,
		"versions": versions,
	}
	return render(request, "pdf_detail.html", context)

# def preview(request, slug=None):
# 	file_path = settings.MEDIA_URL + /
# 	pdf_data = open("/path/to/my/image.pdf", "rb").read()
# 	return HttpResponse(pdf_data, mimetype="application/pdf")


@login_required
def pdf_update(request, slug=None):
	instance = get_object_or_404(PDF, slug=slug)
	form = PDFForm(request.POST or None, request.FILES or None, instance=instance)
	if form.is_valid():
		with reversion.create_revision():
			instance = form.save(commit=False)
			instance.save()
			reversion.set_user(request.user)
    		# reversion.set_comment(instance.comment)
		messages.success(request, "<a href='#'>Item</a> Saved", extra_tags='html_safe')
		return HttpResponseRedirect(instance.get_absolute_url())

	context = {
		"title": instance.title,
		"instance": instance,
		"form":form,
	}
	return render(request, "pdf_form.html", context)



class PDFContributorsToggle(RedirectView):
    def get_redirect_url(self, *args, **kwargs):
        slug = self.kwargs.get("pdf")
        username = self.kwargs.get("username")

        obj = get_object_or_404(PDF, slug=slug)
        url_ = obj.get_absolute_url()
        user = get_object_or_404(User, username=username)

        if obj.user == self.request.user:
            if user in obj.contributor.all():
                obj.contributor.remove(user)
                print 'no'
            else:
                obj.contributor.add(user)
                user.profile.notify_invited(pdf=obj,invited_user=user)
                print 'yes'
        else:
            pass
        return url_

# def pdf_delete(request, slug=None):
# 	if not request.user.is_staff or not request.user.is_superuser:
# 		raise Http404
# 	instance = get_object_or_404(Post, slug=slug)
# 	instance.delete()
# 	messages.success(request, "Successfully deleted")
# 	return redirect("posts:list")

templates/base.html
{% load staticfiles %}
<!DOCTYPE html>
<!-- saved from url=(0052)http://getbootstrap.com/docs/4.0/examples/dashboard/ -->
<html lang="en"><head><meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="http://getbootstrap.com/favicon.ico">

    {% block title %}<title>Annotation Home</title>{% endblock %}

    <!-- Bootstrap core CSS -->
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="{% static 'css/dashboard.css' %}" rel="stylesheet">
    <link href="{% static 'css/custom.css' %}" rel="stylesheet">

  <style type="text/css">/* Chart.js */
@-webkit-keyframes chartjs-render-animation{from{opacity:0.99}to{opacity:1}}@keyframes chartjs-render-animation{from{opacity:0.99}to{opacity:1}}.chartjs-render-monitor{-webkit-animation:chartjs-render-animation 0.001s;animation:chartjs-render-animation 0.001s;}</style></head>
  {% block style %}

  {% endblock %}
  <body>
    <div class="container-fluid">
      <nav class="navbar navbar-dark sticky-top nav-bg-color flex-md-nowrap p-0">
        <a class="navbar-brand col-sm-3 col-md-2 mr-0" href="{% url 'accounts:home' %}">PDF Annotation</a>
        {% if request.user.is_authenticated %}
          <input class="form-control form-control-dark w-100" type="text" placeholder="Search" aria-label="Search">
          <ul class="navbar-nav px-3">
            <li class="nav-item text-nowrap">
              <a class="nav-link" href="{% url 'accounts:logout' %}">Sign out</a>
            </li>
          </ul>
        {% endif %}
      </nav>
      {% block content %}

      {% endblock %}
    </div>
    
    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="{% static 'js/jquery-3.2.1.slim.min.js' %}"></script>
    <script>window.jQuery || document.write('<script src="{% static 'js/jquery-slim.min.js' %}"><\/script>')</script>
    <script src="{% static 'js/popper.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>

    <!-- Icons -->
    <script src="{% static 'js/feather.min.js' %}"></script>
    <script>
      feather.replace()
    </script>

    <!-- Graphs -->
    <script src="{% static 'js/Chart.min.js' %}"></script>
    <script>
      var ctx = document.getElementById("myChart");
      var myChart = new Chart(ctx, {
        type: 'line',
        data: {
          labels: ["Sunday", "Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday"],
          datasets: [{
            data: [15339, 21345, 18483, 24003, 23489, 24092, 12034],
            lineTension: 0,
            backgroundColor: 'transparent',
            borderColor: '#007bff',
            borderWidth: 4,
            pointBackgroundColor: '#007bff'
          }]
        },
        options: {
          scales: {
            yAxes: [{
              ticks: {
                beginAtZero: false
              }
            }]
          },
          legend: {
            display: false,
          }
        }
      });
    </script>
    {% block javascript %}

    {% endblock %}
</body>
</html>

templates/login.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block title %}<title>Login</title>{% endblock %}

{% block style %}
    <!-- Custom styles for this template -->
    <link href="{% static 'css/floating-labels.css' %}" rel="stylesheet">
{% endblock %}

{% block content %}
    <div class="container">
      <form class="form-signin" method='POST' action="." enctype='multipart/form-data'>{% csrf_token %}
        <div class="text-center mb-4">
          <img class="mb-4" src="{% static 'img/PDF.ico' %}" alt="" width="72" height="72">
          <h1 class="h3 mb-3 font-weight-normal">PDF Annotation</h1>
        </div>
        <h4>Please login</h4>
        <div class="form-label-group">
          <!-- <input type="email" id="inputEmail" class="form-control" placeholder="Email address" required="" autofocus=""> -->
          {{ form.username }}
          <label for="inputEmail">Username</label>
        </div>

        <div class="form-label-group">
          <!-- <input type="password" id="inputPassword" class="form-control" placeholder="Password" required=""> -->
          {{ form.password }}
          <label for="inputPassword">Password</label>
        </div>

        <div class="checkbox mb-3">
          <label>
            <input type="checkbox" value="remember-me"> Remember me
          </label>
        </div>
        <button class="btn btn-lg btn-primary btn-block" type="submit">Sign in</button>
        <p class="mt-5 mb-3 text-muted text-center">© 2017-2018</p>
      </form>
    
      <div class="row">
        <div class="col-sm-6 offset-2">
          <div class="text-center">
            <a class="d-block  mt-3" href="{% url 'accounts:register' %}">Need an account? Register an Account</a>
            <a class="d-block " href="forgot-password.html">Forgot Password?</a>
          </div>
        </div>
      </div>
    </div>
    
{% endblock %}

{% block javascript %}

{% endblock %}

templates/notifications.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block title %}{% endblock %}

{% block style %}

{% endblock %}

{% block content %}
    <div class="container-fluid">
      <div class="row">
        {% include 'sidebar.html' %}
        <div class="col-md-7 offset-2">
          <main role="main" class="container">
            <div class="my-3 p-3 bg-white rounded box-shadow">
              <h4 class="border-bottom border-gray pb-2 ">Notifications</h4>
              {% if notifications %}
                {% for notification in notifications %}
                  <div class="media text-muted pt-3">
                    <img data-src="holder.js/32x32?theme=thumb&amp;bg=007bff&amp;fg=007bff&amp;size=1" alt="32x32" class="mr-2 rounded" style="width: 32px; height: 32px;" src="data:image/svg+xml;charset=UTF-8,%3Csvg%20width%3D%2232%22%20height%3D%2232%22%20xmlns%3D%22http%3A%2F%2Fwww.w3.org%2F2000%2Fsvg%22%20viewBox%3D%220%200%2032%2032%22%20preserveAspectRatio%3D%22none%22%3E%3Cdefs%3E%3Cstyle%20type%3D%22text%2Fcss%22%3E%23holder_1618aad4406%20text%20%7B%20fill%3A%23007bff%3Bfont-weight%3Abold%3Bfont-family%3AArial%2C%20Helvetica%2C%20Open%20Sans%2C%20sans-serif%2C%20monospace%3Bfont-size%3A2pt%20%7D%20%3C%2Fstyle%3E%3C%2Fdefs%3E%3Cg%20id%3D%22holder_1618aad4406%22%3E%3Crect%20width%3D%2232%22%20height%3D%2232%22%20fill%3D%22%23007bff%22%3E%3C%2Frect%3E%3Cg%3E%3Ctext%20x%3D%2212.046875%22%20y%3D%2217.2%22%3E32x32%3C%2Ftext%3E%3C%2Fg%3E%3C%2Fg%3E%3C%2Fsvg%3E" data-holder-rendered="true">
                    <!-- <p class="media-body pb-3 mb-0 lh-125 border-bottom border-gray">
                      <strong class="d-block text-gray-dark">@{{ notification.from_user }}</strong>
                      {{ notification|safe }}

                    </p> -->
                    <div class="media-body pb-3 mb-0 lh-125 border-bottom border-gray">
                      <div class="d-flex justify-content-between align-items-center w-100">
                        <strong class="text-gray-dark">@{{ notification.from_user }}</strong>
                        {% if not notification.is_reverted and notification.need_response %}
                          <span>
                            <a href="{% url 'accounts:invite_accept' notification.id %}" class="br-3 btn btn-success">Accept</a>
                            <a href="{% url 'accounts:invite_reject' notification.id %}" class="btn btn-primary">Reject</a>
                          </span>
                        {% endif %}
                      </div>
                      <span class="d-block">{{ notification|safe }}</span>
                    </div>
                  </div>
                {% endfor %}
              {% else %}
                <h3>Sorry {{ request.user }}you dont have any notification.</h3>
              {% endif %}
              
              <small class="d-block text-right mt-3">
                <a href="http://getbootstrap.com/docs/4.0/examples/offcanvas/#">All updates</a>
              </small>
            </div>
            

            <div class="my-3 p-3 bg-white rounded box-shadow">
              <h6 class="border-bottom border-gray pb-2 mb-0">Suggestions</h6>
              <div class="media text-muted pt-3">
                <img data-src="holder.js/32x32?theme=thumb&amp;bg=007bff&amp;fg=007bff&amp;size=1" alt="32x32" class="mr-2 rounded" src="data:image/svg+xml;charset=UTF-8,%3Csvg%20width%3D%2232%22%20height%3D%2232%22%20xmlns%3D%22http%3A%2F%2Fwww.w3.org%2F2000%2Fsvg%22%20viewBox%3D%220%200%2032%2032%22%20preserveAspectRatio%3D%22none%22%3E%3Cdefs%3E%3Cstyle%20type%3D%22text%2Fcss%22%3E%23holder_1618aad4434%20text%20%7B%20fill%3A%23007bff%3Bfont-weight%3Abold%3Bfont-family%3AArial%2C%20Helvetica%2C%20Open%20Sans%2C%20sans-serif%2C%20monospace%3Bfont-size%3A2pt%20%7D%20%3C%2Fstyle%3E%3C%2Fdefs%3E%3Cg%20id%3D%22holder_1618aad4434%22%3E%3Crect%20width%3D%2232%22%20height%3D%2232%22%20fill%3D%22%23007bff%22%3E%3C%2Frect%3E%3Cg%3E%3Ctext%20x%3D%2212.046875%22%20y%3D%2217.2%22%3E32x32%3C%2Ftext%3E%3C%2Fg%3E%3C%2Fg%3E%3C%2Fsvg%3E" data-holder-rendered="true" style="width: 32px; height: 32px;">
                <div class="media-body pb-3 mb-0 small lh-125 border-bottom border-gray">
                  <div class="d-flex justify-content-between align-items-center w-100">
                    <strong class="text-gray-dark">Full Name</strong>
                    <a href="http://getbootstrap.com/docs/4.0/examples/offcanvas/#">Follow</a>
                  </div>
                  <span class="d-block">@username</span>
                </div>
              </div>
              <div class="media text-muted pt-3">
                <img data-src="holder.js/32x32?theme=thumb&amp;bg=007bff&amp;fg=007bff&amp;size=1" alt="32x32" class="mr-2 rounded" src="data:image/svg+xml;charset=UTF-8,%3Csvg%20width%3D%2232%22%20height%3D%2232%22%20xmlns%3D%22http%3A%2F%2Fwww.w3.org%2F2000%2Fsvg%22%20viewBox%3D%220%200%2032%2032%22%20preserveAspectRatio%3D%22none%22%3E%3Cdefs%3E%3Cstyle%20type%3D%22text%2Fcss%22%3E%23holder_1618aad4437%20text%20%7B%20fill%3A%23007bff%3Bfont-weight%3Abold%3Bfont-family%3AArial%2C%20Helvetica%2C%20Open%20Sans%2C%20sans-serif%2C%20monospace%3Bfont-size%3A2pt%20%7D%20%3C%2Fstyle%3E%3C%2Fdefs%3E%3Cg%20id%3D%22holder_1618aad4437%22%3E%3Crect%20width%3D%2232%22%20height%3D%2232%22%20fill%3D%22%23007bff%22%3E%3C%2Frect%3E%3Cg%3E%3Ctext%20x%3D%2212.046875%22%20y%3D%2217.2%22%3E32x32%3C%2Ftext%3E%3C%2Fg%3E%3C%2Fg%3E%3C%2Fsvg%3E" data-holder-rendered="true" style="width: 32px; height: 32px;">
                <div class="media-body pb-3 mb-0 small lh-125 border-bottom border-gray">
                  <div class="d-flex justify-content-between align-items-center w-100">
                    <strong class="text-gray-dark">Full Name</strong>
                    <a href="http://getbootstrap.com/docs/4.0/examples/offcanvas/#">Follow</a>
                  </div>
                  <span class="d-block">@username</span>
                </div>
              </div>
              <div class="media text-muted pt-3">
                <img data-src="holder.js/32x32?theme=thumb&amp;bg=007bff&amp;fg=007bff&amp;size=1" alt="32x32" class="mr-2 rounded" src="data:image/svg+xml;charset=UTF-8,%3Csvg%20width%3D%2232%22%20height%3D%2232%22%20xmlns%3D%22http%3A%2F%2Fwww.w3.org%2F2000%2Fsvg%22%20viewBox%3D%220%200%2032%2032%22%20preserveAspectRatio%3D%22none%22%3E%3Cdefs%3E%3Cstyle%20type%3D%22text%2Fcss%22%3E%23holder_1618aad443b%20text%20%7B%20fill%3A%23007bff%3Bfont-weight%3Abold%3Bfont-family%3AArial%2C%20Helvetica%2C%20Open%20Sans%2C%20sans-serif%2C%20monospace%3Bfont-size%3A2pt%20%7D%20%3C%2Fstyle%3E%3C%2Fdefs%3E%3Cg%20id%3D%22holder_1618aad443b%22%3E%3Crect%20width%3D%2232%22%20height%3D%2232%22%20fill%3D%22%23007bff%22%3E%3C%2Frect%3E%3Cg%3E%3Ctext%20x%3D%2212.046875%22%20y%3D%2217.2%22%3E32x32%3C%2Ftext%3E%3C%2Fg%3E%3C%2Fg%3E%3C%2Fsvg%3E" data-holder-rendered="true" style="width: 32px; height: 32px;">
                <div class="media-body pb-3 mb-0 small lh-125 border-bottom border-gray">
                  <div class="d-flex justify-content-between align-items-center w-100">
                    <strong class="text-gray-dark">Full Name</strong>
                    <a href="http://getbootstrap.com/docs/4.0/examples/offcanvas/#">Follow</a>
                  </div>
                  <span class="d-block">@username</span>
                </div>
              </div>
              <small class="d-block text-right mt-3">
                <a href="http://getbootstrap.com/docs/4.0/examples/offcanvas/#">All suggestions</a>
              </small>
            </div>
          </main>
        </div>
      </div>
    </div>

{% endblock %}

{% block javascript %}

{% endblock %}

templates/pdf_detail.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block title %}<title>Create</title>{% endblock %}

{% block style %}
    <link rel="stylesheet" type="text/css" href="{% static 'css/custom-drag-and-drop.css' %}">
    <link rel="stylesheet" href="http://code.jquery.com/ui/1.8.18/themes/base/jquery-ui.css" type="text/css" media="all" />
{% endblock %}

{% block content %}
<div class="container-fluid">
	<div class="row">
		<div class="col-sm-2">
			{% include 'sidebar.html' %}
		</div>
		<div class="col-sm-6"><br>
			<div class="card flex-md-row mb-4 box-shadow h-md-250">
				<img class="card-img-left flex-auto d-none d-md-block" src="{% static 'img/pdf1.png' %}" alt="Card image cap">
	            <div class="card-body d-flex flex-column align-items-start">
	              <h3 class="mb-0">
	                <a class="text-dark" href="#">{{ instance.title }}</a>
	              </h3>
	              <div class="mb-1 text-muted">{{ instance.timestamp }}</div>
	              <div class="mb-1 text-muted">{{ instance.contributor.count }} contributors</div>
	              <div class="mb-1 text-muted">last updated: {{ instance.updated }}</div>
	              <div class="btn-group mr-2">

	              	{% if request.user == instance.user %}
		                <button type="button" class="btn btn-outline-primary" data-toggle="modal" data-target="#exampleModalCenter">
						  Share
						</button>
					{% endif %}

					<!-- Modal -->
					<div class="modal fade" id="exampleModalCenter" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
					  <div class="modal-dialog modal-dialog-centered" role="document">
					    <div class="modal-content">
					      <div class="modal-header">
					        <h5 class="modal-title" id="exampleModalLongTitle">Invite Users</h5>
					        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
					          <span aria-hidden="true">&times;</span>
					        </button>
					      </div>
					      <div class="modal-body">
					        <div class="container">
							  <div class="row">
							    <div class="col-md-12">
							        <input type="text" name="search" id="invites" placeholder="Search accounts..." class="form-control">
							          
							        <ul id="invites_results"></ul>
							    </div>
							  </div>
							</div>
					      </div>
					      <div class="modal-footer">

					      </div>
					    </div>
					  </div>
					</div>
	                <a class="btn btn-sm btn-outline-secondary" href="{% url 'pdfs:update' slug=instance.slug %}">update</a>
	                <a class="btn btn-sm btn-outline-primary" href="{{ instance.file.url }}">Preview</a>
	              </div>
	            </div>
	        </div>
	        <section class="mt-4">
	        	<table class="table table-hover">
				  <thead>
				    <tr>
				      <th scope="col">#</th>
				      <th scope="col">Title</th>
				      <th scope="col">User</th>
				      <th scope="col">Comment</th>
				      <th scope="col">Date</th>
				    </tr>
				  </thead>
				  <tbody>
				  	{% for version in versions %}
					    <tr>
					      <th scope="row">{{ forloop.counter }}</th>
					      <td>{{ version }}</td>
					      <td>{{ version.revision.user }}</td>
					      <td>{{ version.field_dict.comment }}</td>
					      <td>{{ version.revision.date_created }}</td>
					    </tr>
				    {% endfor %}
				  </tbody>
				</table>
	        </section>
		</div>
		<div class="col-sm-3">
			{% include 'page_sidebar.html' %}
		</div>
	</div>
</div>
	
	
{% endblock %}

{% block javascript %}
	<script src="{% static 'js/ajax/jquery.min.js' %}" type="text/javascript"></script>
	<script type="text/javascript">
		$("#invites").keyup(function () {
	      var username = $(this).val();
	      var pdf_slug = '{{ instance.slug }}';
	      $.ajax({
	      	type:"GET",
	        url: "{% url 'accounts:get_invites' %}",
	        data: {
	          'username': username,
	          'pdf': pdf_slug,
	        },
	        dataType: 'html',
	        success: function(data){
		    	$('#invites_results').html(data)
		    },
	        error: function(){
	          console.log("Error :/")
	          }
	      });
	    });
	</script>
{% endblock %}